package cn.pacificimmi.common;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

import cn.pacificimmi.common.models.base.BaseDictionary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dict extends BaseDictionary<Dict>{
	public static final Dict dao = new Dict();
	private List<Dict> subDictionaries = new ArrayList<Dict>();
	public List<Dict> getSubDictionaries() {
		return subDictionaries;
	}
	
	public void setSubDictionaries(List<Dict> subDictionaries) {
		this.subDictionaries = subDictionaries;
	}
	
	public void addDictionary(Dict dict){
		subDictionaries.add(dict);
		Collections.sort(subDictionaries, new SortMethod());
	}
	
	class SortMethod implements Comparator<Dict>{ 
		@Override
		public int compare(Dict o1, Dict o2) {
			  if (o1.getSort() > o2.getSort())
			   return 1;
			return 0;
		}
		
	}
}
