package cn.pacificimmi.common.models;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("crm_business_cooperation", "id", BusinessCooperation.class);//商务合作
		arp.addMapping("crm_business_negotiation", "id", BusinessNegotiation.class);//商务合作洽谈状态
		arp.addMapping("crm_immigration_policy", "id", ImmigrationPolicy.class);//移民政策

		arp.addMapping("wx_estimate_question", "estimate_question_id", EstimateQuestion.class);
		arp.addMapping("wx_estimate_record", "estimate_record_id", EstimateRecord.class);
		arp.addMapping("wx_estimate_select", "estimate_select_id", EstimateSelect.class);
		arp.addMapping("wx_estimate_select_additional", "estimate_select_additional_id", EstimateSelectAdditional.class);
		arp.addMapping("wx_estimate_question_version", "version_id", EstimateQuestionVersion.class);
		
		arp.addMapping("crm_section", "section_id", Section.class);
		arp.addMapping("console_websys", "sys_id", Websys.class);
		arp.addMapping("crm_country", "id", Country.class);//国家
		arp.addMapping("crm_cust_signinfo", "signed_id", CustSigninfo.class);
		arp.addMapping("crm_custinfo_intention", "intention_id", CustinfoIntention.class);
		arp.addMapping("crm_letters", "letter_id", Letters.class);
		arp.addMapping("crm_project_apply_process", "project_apply_process_id", ProjectApplyProcess.class);
		arp.addMapping("crm_signinfo_annex", "id", SigninfoAnnex.class);
		arp.addMapping("crm_topics", "topic_id", Topics.class);
		
		arp.addMapping("console_dictionary", "dict_id", Dictionary.class);
		arp.addMapping("console_orgnization", "org_id", Orgnization.class);
		// Composite Primary Key order: org_id,sys_id
		arp.addMapping("console_orgnization_websys", "org_id,sys_id", OrgnizationWebsys.class);
		arp.addMapping("console_resource", "res_id", Resource.class);
		arp.addMapping("console_role", "role_id", Role.class);
		// Composite Primary Key order: res_id,role_id
		arp.addMapping("console_role_resource", "res_id,role_id", RoleResource.class);
		// Composite Primary Key order: role_id,station_id
		arp.addMapping("console_role_station", "role_id,station_id", RoleStation.class);
		arp.addMapping("console_station", "station_id", Station.class);
		arp.addMapping("console_user", "user_id", User.class);
		// Composite Primary Key order: station_id,user_id
		arp.addMapping("console_user_station", "station_id,user_id", UserStation.class);

		arp.addMapping("crm_address_city", "CityId", AddressCity.class);
		arp.addMapping("crm_address_country", "CountryId", AddressCountry.class);
		arp.addMapping("crm_address_province", "ProvinceId", AddressProvince.class);
		arp.addMapping("crm_cust_edit_log", "id", CustEditLog.class);
		arp.addMapping("crm_cust_follow_records", "follow_record_id", CustFollowRecords.class);

		arp.addMapping("crm_custinfo", "custinfo_id", Custinfo.class);
		arp.addMapping("crm_custinfo_invoice", "custinfo_invoice_id", CustinfoInvoice.class);
		arp.addMapping("crm_custinfo_receive", "custinfo_receive_id", CustinfoReceive.class);
		arp.addMapping("crm_custinfo_security", "custinfo_security_id", CustinfoSecurity.class);
		arp.addMapping("crm_custinfo_steward", "id", CustinfoSteward.class);
		arp.addMapping("crm_custinfo_feedback", "custinfo_feedback_id", CustinfoFeedback.class);
		
		arp.addMapping("crm_distribution_main", "distribution_main_id", DistributionMain.class);
		arp.addMapping("crm_distribution_scale", "distribution_scale_id", DistributionScale.class);
		arp.addMapping("crm_distribution_set", "distribution_set_id", DistributionSet.class);
		arp.addMapping("crm_distribution_type", "distribution_type_id", DistributionType.class);
		arp.addMapping("crm_proxy_status_record", "proxy_status_record_id", ProxyStatusRecord.class);
		
		arp.addMapping("crm_project", "project_id", Project.class);
		arp.addMapping("crm_project_cost", "project_cost_id", ProjectCost.class);
		arp.addMapping("crm_project_material", "project_material_id", ProjectMaterial.class);
		arp.addMapping("crm_project_expands", "project_expands_id", ProjectExpands.class);
		arp.addMapping("crm_project_resource", "project_resource_id", ProjectResource.class);
		
		arp.addMapping("crm_steward_evaluate", "evaluate_id", StewardEvaluate.class);
		arp.addMapping("crm_steward_like", "like_id", StewardLike.class);
		arp.addMapping("crm_steward_sign", "sign_id", StewardSign.class);
		arp.addMapping("crm_steward_user", "steward_id", StewardUser.class);
		
		arp.addMapping("wx_card_access", "card_access_id", CardAccess.class);
		arp.addMapping("wx_card_customer", "card_customer_id", CardCustomer.class);
		arp.addMapping("wx_weixin_resource", "weixin_resource_id", WeixinResource.class);
		arp.addMapping("crm_information_img", "info_id", InformationImg.class);
		arp.addMapping("crm_information_article", "info_id", InformationArticle.class);
		arp.addMapping("console_operation_log", "id", OperationLog.class);
		arp.addMapping("crm_activity", "activity_id", Activity.class);
		arp.addMapping("crm_city", "id", City.class);//城市
		arp.addMapping("crm_activity_sign", "sign_id", ActivitySign.class);
		
		arp.addMapping("portal_channel", "channel_id", Channel.class);
		arp.addMapping("portal_live", "live_id", Live.class);
		arp.addMapping("portal_live_application", "application_id", LiveApplication.class);
		arp.addMapping("portal_live_message", "message_id", LiveMessage.class);
		arp.addMapping("portal_invitation_code", "id", InvitationCode.class);
		
		arp.addMapping("official_configs", "oc_id", Configs.class);
		arp.addMapping("official_recruitment", "or_id", Recruitment.class);
		arp.addMapping("crm_topic_setting", "setting_id", TopicSetting.class);
		arp.addMapping("official_honor", "oh_id", Honor.class);
		arp.addMapping("official_honor_imgs", "ohi_id", HonorImgs.class);
		arp.addMapping("official_about_nav", "oan_id", AboutNav.class);
		arp.addMapping("crm_professional_team", "team_id", ProfessionalTeam.class);
		
		arp.addMapping("official_copyright", "copyright_id", Copyright.class);
		arp.addMapping("official_friendly_link", "friendly_link_id", FriendlyLink.class);
		arp.addMapping("official_nav_menu", "nav_menu_id", NavMenu.class);
		arp.addMapping("official_page_footers", "page_footers_id", PageFooters.class);
		arp.addMapping("official_page_headers", "page_headers_id", PageHeaders.class);
		arp.addMapping("official_memorabilia", "id", Memorabilia.class);
		arp.addMapping("official_custinfo_message", "custinfo_message_id", CustinfoMessage.class);
	}
}

