package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseAboutNav;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AboutNav extends BaseAboutNav<AboutNav> {
	public static final AboutNav dao = new AboutNav();
}
