package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseActivitySign;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActivitySign extends BaseActivitySign<ActivitySign> {
	public static final ActivitySign dao = new ActivitySign();
}
