package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseActivity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Activity extends BaseActivity<Activity> {
	public static final Activity dao = new Activity();
}
