package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseAddressProvince;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AddressProvince extends BaseAddressProvince<AddressProvince> {
	public static final AddressProvince dao = new AddressProvince();
}
