package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseAddressCountry;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AddressCountry extends BaseAddressCountry<AddressCountry> {
	public static final AddressCountry dao = new AddressCountry();
}
