package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseAddressCity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AddressCity extends BaseAddressCity<AddressCity> {
	public static final AddressCity dao = new AddressCity();
}
