package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseBusinessNegotiation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusinessNegotiation extends BaseBusinessNegotiation<BusinessNegotiation> {
	public static final BusinessNegotiation dao = new BusinessNegotiation();
}
