package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseBusinessCooperation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusinessCooperation extends BaseBusinessCooperation<BusinessCooperation> {
	public static final BusinessCooperation dao = new BusinessCooperation();
}
