package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseCardAccess;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CardAccess extends BaseCardAccess<CardAccess> {
	public static final CardAccess dao = new CardAccess();
}
