package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseCardCustomer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CardCustomer extends BaseCardCustomer<CardCustomer> {
	public static final CardCustomer dao = new CardCustomer();
}
