package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseChannel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Channel extends BaseChannel<Channel> {
	public static final Channel dao = new Channel();
}
