package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseCity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class City extends BaseCity<City> {
	public static final City dao = new City();
}
