package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseConfigs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Configs extends BaseConfigs<Configs> {
	public static final Configs dao = new Configs();
}
