package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseCopyright;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Copyright extends BaseCopyright<Copyright> {
	public static final Copyright dao = new Copyright();
}
