package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseCountry;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Country extends BaseCountry<Country> {
	public static final Country dao = new Country();
}
