package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseCustinfoInvoice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustinfoInvoice extends BaseCustinfoInvoice<CustinfoInvoice> {
	public static final CustinfoInvoice dao = new CustinfoInvoice();
}
