package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseCustinfoSteward;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustinfoSteward extends BaseCustinfoSteward<CustinfoSteward> {
	public static final CustinfoSteward dao = new CustinfoSteward();
}
