package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseCustinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Custinfo extends BaseCustinfo<Custinfo> {
	public static final Custinfo dao = new Custinfo();
}
