package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseCustEditLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustEditLog extends BaseCustEditLog<CustEditLog> {
	public static final CustEditLog dao = new CustEditLog();
}
