package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseCustSigninfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustSigninfo extends BaseCustSigninfo<CustSigninfo> {
	public static final CustSigninfo dao = new CustSigninfo();
}
