package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseCustinfoIntention;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustinfoIntention extends BaseCustinfoIntention<CustinfoIntention> {
	public static final CustinfoIntention dao = new CustinfoIntention();
}
