package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseCustinfoReceive;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustinfoReceive extends BaseCustinfoReceive<CustinfoReceive> {
	public static final CustinfoReceive dao = new CustinfoReceive();
}
