package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseCustFollowRecords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustFollowRecords extends BaseCustFollowRecords<CustFollowRecords> {
	public static final CustFollowRecords dao = new CustFollowRecords();
}
