package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseCustinfoFeedback;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustinfoFeedback extends BaseCustinfoFeedback<CustinfoFeedback> {
	public static final CustinfoFeedback dao = new CustinfoFeedback();
}
