package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseCustinfoSecurity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustinfoSecurity extends BaseCustinfoSecurity<CustinfoSecurity> {
	public static final CustinfoSecurity dao = new CustinfoSecurity();
}
