package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseCustinfoMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustinfoMessage extends BaseCustinfoMessage<CustinfoMessage> {
	public static final CustinfoMessage dao = new CustinfoMessage();
}
