package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseDictionary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dictionary extends BaseDictionary<Dictionary> {
	public static final Dictionary dao = new Dictionary();
}
