package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseDistributionSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DistributionSet extends BaseDistributionSet<DistributionSet> {
	public static final DistributionSet dao = new DistributionSet();
}
