package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseDistributionMain;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DistributionMain extends BaseDistributionMain<DistributionMain> {
	public static final DistributionMain dao = new DistributionMain();
}
