package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseDistributionScale;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DistributionScale extends BaseDistributionScale<DistributionScale> {
	public static final DistributionScale dao = new DistributionScale();
}
