package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseDistributionType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DistributionType extends BaseDistributionType<DistributionType> {
	public static final DistributionType dao = new DistributionType();
}
