package cn.pacificimmi.common.models;

import java.util.ArrayList;
import java.util.List;

import cn.pacificimmi.common.Dict;
import cn.pacificimmi.common.models.base.BaseEstimateSelect;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EstimateSelect extends BaseEstimateSelect<EstimateSelect> {
	public static final EstimateSelect dao = new EstimateSelect();
	
	private List<EstimateSelectAdditional> esaList = new ArrayList<EstimateSelectAdditional>();
	private List<Dict> dictList = new ArrayList<Dict>();

	public List<EstimateSelectAdditional> getEsaList() {
		return esaList;
	}

	public void setEsaList(List<EstimateSelectAdditional> esaList) {
		this.esaList = esaList;
	}

	public List<Dict> getDictList() {
		return dictList;
	}

	public void setDictList(List<Dict> dictList) {
		this.dictList = dictList;
	}
	
	
	
}
