package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseEstimateQuestionVersion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EstimateQuestionVersion extends BaseEstimateQuestionVersion<EstimateQuestionVersion> {
	public static final EstimateQuestionVersion dao = new EstimateQuestionVersion();
}
