package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseEstimateQuestion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EstimateQuestion extends BaseEstimateQuestion<EstimateQuestion> {
	public static final EstimateQuestion dao = new EstimateQuestion();
}
