package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseEstimateSelectAdditional;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EstimateSelectAdditional extends BaseEstimateSelectAdditional<EstimateSelectAdditional> {
	public static final EstimateSelectAdditional dao = new EstimateSelectAdditional();
}
