package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseEstimateRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EstimateRecord extends BaseEstimateRecord<EstimateRecord> {
	public static final EstimateRecord dao = new EstimateRecord();
}
