package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseFriendlyLink;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FriendlyLink extends BaseFriendlyLink<FriendlyLink> {
	public static final FriendlyLink dao = new FriendlyLink();
}
