package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseHonorImgs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HonorImgs extends BaseHonorImgs<HonorImgs> {
	public static final HonorImgs dao = new HonorImgs();
}
