package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseHonor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Honor extends BaseHonor<Honor> {
	public static final Honor dao = new Honor();
}
