package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseImmigrationPolicy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ImmigrationPolicy extends BaseImmigrationPolicy<ImmigrationPolicy> {
	public static final ImmigrationPolicy dao = new ImmigrationPolicy();
}
