package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseInformationImg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InformationImg extends BaseInformationImg<InformationImg> {
	public static final InformationImg dao = new InformationImg();
}
