package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseInformationArticle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InformationArticle extends BaseInformationArticle<InformationArticle> {
	public static final InformationArticle dao = new InformationArticle();
}
