package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseInvitationCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InvitationCode extends BaseInvitationCode<InvitationCode> {
	public static final InvitationCode dao = new InvitationCode();
}
