package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseLetters;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Letters extends BaseLetters<Letters> {
	public static final Letters dao = new Letters();
}
