package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseLiveLike;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LiveLike extends BaseLiveLike<LiveLike> {
	public static final LiveLike dao = new LiveLike();
}
