package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseLive;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Live extends BaseLive<Live> {
	public static final Live dao = new Live();
}
