package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseLiveMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LiveMessage extends BaseLiveMessage<LiveMessage> {
	public static final LiveMessage dao = new LiveMessage();
}
