package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseLiveApplication;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LiveApplication extends BaseLiveApplication<LiveApplication> {
	public static final LiveApplication dao = new LiveApplication();
}
