package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseMemorabilia;

/**
 * Generated by JFinal.
 * 公司大事记表
 */
@SuppressWarnings("serial")
public class Memorabilia extends BaseMemorabilia<Memorabilia> {
	public static final Memorabilia dao = new Memorabilia();
}
