package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Message extends BaseMessage<Message> {
	public static final Message dao = new Message();
}
