package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseNavMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NavMenu extends BaseNavMenu<NavMenu> {
	public static final NavMenu dao = new NavMenu();
}
