package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseOperationLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OperationLog extends BaseOperationLog<OperationLog> {
	public static final OperationLog dao = new OperationLog();
}
