package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseOrgnization;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Orgnization extends BaseOrgnization<Orgnization> {
	public static final Orgnization dao = new Orgnization();
}
