package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseOrgnizationWebsys;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrgnizationWebsys extends BaseOrgnizationWebsys<OrgnizationWebsys> {
	public static final OrgnizationWebsys dao = new OrgnizationWebsys();
}
