package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BasePageHeaders;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PageHeaders extends BasePageHeaders<PageHeaders> {
	public static final PageHeaders dao = new PageHeaders();
}
