package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BasePageFooters;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PageFooters extends BasePageFooters<PageFooters> {
	public static final PageFooters dao = new PageFooters();
}
