package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseProfessionalTeam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProfessionalTeam extends BaseProfessionalTeam<ProfessionalTeam> {
	public static final ProfessionalTeam dao = new ProfessionalTeam();
}
