package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseProjectMaterial;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectMaterial extends BaseProjectMaterial<ProjectMaterial> {
	public static final ProjectMaterial dao = new ProjectMaterial();
}
