package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseProjectResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectResource extends BaseProjectResource<ProjectResource> {
	public static final ProjectResource dao = new ProjectResource();
}
