package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseProject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Project extends BaseProject<Project> {
	public static final Project dao = new Project();
}
