package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseProjectExpands;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectExpands extends BaseProjectExpands<ProjectExpands> {
	public static final ProjectExpands dao = new ProjectExpands();
}
