package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseProjectApplyProcess;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectApplyProcess extends BaseProjectApplyProcess<ProjectApplyProcess> {
	public static final ProjectApplyProcess dao = new ProjectApplyProcess();
}
