package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseProjectCost;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectCost extends BaseProjectCost<ProjectCost> {
	public static final ProjectCost dao = new ProjectCost();
}
