package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseProxyStatusRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProxyStatusRecord extends BaseProxyStatusRecord<ProxyStatusRecord> {
	public static final ProxyStatusRecord dao = new ProxyStatusRecord();
}
