package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseRecruitment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Recruitment extends BaseRecruitment<Recruitment> {
	public static final Recruitment dao = new Recruitment();
}
