package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Resource extends BaseResource<Resource> {
	public static final Resource dao = new Resource();
}
