package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseRoleStation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleStation extends BaseRoleStation<RoleStation> {
	public static final RoleStation dao = new RoleStation();
}
