package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseRoleResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleResource extends BaseRoleResource<RoleResource> {
	public static final RoleResource dao = new RoleResource();
}
