package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseSection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Section extends BaseSection<Section> {
	public static final Section dao = new Section();
}
