package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseSigninfoAnnex;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SigninfoAnnex extends BaseSigninfoAnnex<SigninfoAnnex> {
	public static final SigninfoAnnex dao = new SigninfoAnnex();
}
