package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseStation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Station extends BaseStation<Station> {
	public static final Station dao = new Station();
}
