package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseStewardLike;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StewardLike extends BaseStewardLike<StewardLike> {
	public static final StewardLike dao = new StewardLike();
}
