package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseStewardEvaluate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StewardEvaluate extends BaseStewardEvaluate<StewardEvaluate> {
	public static final StewardEvaluate dao = new StewardEvaluate();
}
