package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseStewardUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StewardUser extends BaseStewardUser<StewardUser> {
	public static final StewardUser dao = new StewardUser();
}
