package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseStewardSign;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StewardSign extends BaseStewardSign<StewardSign> {
	public static final StewardSign dao = new StewardSign();
}
