package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseTopicSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TopicSetting extends BaseTopicSetting<TopicSetting> {
	public static final TopicSetting dao = new TopicSetting();
}
