package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseTopics;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Topics extends BaseTopics<Topics> {
	public static final Topics dao = new Topics();
}
