package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();
}
