package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseUserStation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserStation extends BaseUserStation<UserStation> {
	public static final UserStation dao = new UserStation();
}
