package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseWebsys;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Websys extends BaseWebsys<Websys> {
	public static final Websys dao = new Websys();
}
