package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseWeixinResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WeixinResource extends BaseWeixinResource<WeixinResource> {
	public static final WeixinResource dao = new WeixinResource();
}
