package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseWxCardAccess;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxCardAccess extends BaseWxCardAccess<WxCardAccess> {
	public static final WxCardAccess dao = new WxCardAccess();
}
