package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseWxCardCustomer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxCardCustomer extends BaseWxCardCustomer<WxCardCustomer> {
	public static final WxCardCustomer dao = new WxCardCustomer();
}
