package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseWxEstimateQuestion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxEstimateQuestion extends BaseWxEstimateQuestion<WxEstimateQuestion> {
	public static final WxEstimateQuestion dao = new WxEstimateQuestion();
}
