package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseWxEstimateSelectAdditional;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxEstimateSelectAdditional extends BaseWxEstimateSelectAdditional<WxEstimateSelectAdditional> {
	public static final WxEstimateSelectAdditional dao = new WxEstimateSelectAdditional();
}
