package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseWxEstimateSelect;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxEstimateSelect extends BaseWxEstimateSelect<WxEstimateSelect> {
	public static final WxEstimateSelect dao = new WxEstimateSelect();
}
