package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseWxWeixinResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxWeixinResource extends BaseWxWeixinResource<WxWeixinResource> {
	public static final WxWeixinResource dao = new WxWeixinResource();
}
