package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDistributionMain<M extends BaseDistributionMain<M>> extends Model<M> implements IBean {

	public void setDistributionMainId(java.lang.Integer distributionMainId) {
		set("distribution_main_id", distributionMainId);
	}

	public java.lang.Integer getDistributionMainId() {
		return get("distribution_main_id");
	}

	public void setModelType(java.lang.String modelType) {
		set("model_type", modelType);
	}

	public java.lang.String getModelType() {
		return get("model_type");
	}

	public void setCliMainId(java.lang.Integer cliMainId) {
		set("cli_main_id", cliMainId);
	}

	public java.lang.Integer getCliMainId() {
		return get("cli_main_id");
	}

	public void setCliParentId(java.lang.Integer cliParentId) {
		set("cli_parent_id", cliParentId);
	}

	public java.lang.Integer getCliParentId() {
		return get("cli_parent_id");
	}

	public void setParentScale(java.lang.String parentScale) {
		set("parent_scale", parentScale);
	}

	public java.lang.String getParentScale() {
		return get("parent_scale");
	}

	public void setCliGrandparentId(java.lang.Integer cliGrandparentId) {
		set("cli_grandparent_id", cliGrandparentId);
	}

	public java.lang.Integer getCliGrandparentId() {
		return get("cli_grandparent_id");
	}

	public void setGrandParentScale(java.lang.String grandParentScale) {
		set("grand_parent_scale", grandParentScale);
	}

	public java.lang.String getGrandParentScale() {
		return get("grand_parent_scale");
	}

	public void setProjectId(java.lang.Integer projectId) {
		set("project_id", projectId);
	}

	public java.lang.Integer getProjectId() {
		return get("project_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setProcessId(java.lang.Integer processId) {
		set("process_id", processId);
	}

	public java.lang.Integer getProcessId() {
		return get("process_id");
	}

	public void setCliTypeId(java.lang.Integer cliTypeId) {
		set("cli_type_id", cliTypeId);
	}

	public java.lang.Integer getCliTypeId() {
		return get("cli_type_id");
	}

	public void setCliSignedStatus(java.lang.String cliSignedStatus) {
		set("cli_signed_status", cliSignedStatus);
	}

	public java.lang.String getCliSignedStatus() {
		return get("cli_signed_status");
	}

	public void setReturnParentStatus(java.lang.String returnParentStatus) {
		set("return_parent_status", returnParentStatus);
	}

	public java.lang.String getReturnParentStatus() {
		return get("return_parent_status");
	}

	public void setReturnParentMoney(java.lang.String returnParentMoney) {
		set("return_parent_money", returnParentMoney);
	}

	public java.lang.String getReturnParentMoney() {
		return get("return_parent_money");
	}

	public void setReturnGrandparentStatus(java.lang.String returnGrandparentStatus) {
		set("return_grandparent_status", returnGrandparentStatus);
	}

	public java.lang.String getReturnGrandparentStatus() {
		return get("return_grandparent_status");
	}

	public void setReturnGrandparentMoney(java.lang.String returnGrandparentMoney) {
		set("return_grandparent_money", returnGrandparentMoney);
	}

	public java.lang.String getReturnGrandparentMoney() {
		return get("return_grandparent_money");
	}

}
