package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseConfigs<M extends BaseConfigs<M>> extends Model<M> implements IBean {

	public void setOcId(java.lang.Integer ocId) {
		set("oc_id", ocId);
	}

	public java.lang.Integer getOcId() {
		return get("oc_id");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}

	public java.lang.String getCode() {
		return get("code");
	}

	public void setValue(java.lang.String value) {
		set("value", value);
	}

	public java.lang.String getValue() {
		return get("value");
	}

	public void setEditor(java.lang.String editor) {
		set("editor", editor);
	}

	public java.lang.String getEditor() {
		return get("editor");
	}

	public void setEditTime(java.util.Date editTime) {
		set("edit_time", editTime);
	}

	public java.util.Date getEditTime() {
		return get("edit_time");
	}

	public void setPublisher(java.lang.String publisher) {
		set("publisher", publisher);
	}

	public java.lang.String getPublisher() {
		return get("publisher");
	}

	public void setPublishTime(java.util.Date publishTime) {
		set("publish_time", publishTime);
	}

	public java.util.Date getPublishTime() {
		return get("publish_time");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

}
