package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustinfoSecurity<M extends BaseCustinfoSecurity<M>> extends Model<M> implements IBean {

	public void setCustinfoSecurityId(java.lang.Integer custinfoSecurityId) {
		set("custinfo_security_id", custinfoSecurityId);
	}

	public java.lang.Integer getCustinfoSecurityId() {
		return get("custinfo_security_id");
	}

	public void setCustinfoId(java.lang.Integer custinfoId) {
		set("custinfo_id", custinfoId);
	}

	public java.lang.Integer getCustinfoId() {
		return get("custinfo_id");
	}

	public void setSecurityNo(java.lang.String securityNo) {
		set("security_no", securityNo);
	}

	public java.lang.String getSecurityNo() {
		return get("security_no");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
