package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEstimateQuestion<M extends BaseEstimateQuestion<M>> extends Model<M> implements IBean {

	public void setEstimateQuestionId(java.lang.Integer estimateQuestionId) {
		set("estimate_question_id", estimateQuestionId);
	}

	public java.lang.Integer getEstimateQuestionId() {
		return get("estimate_question_id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setDictCode(java.lang.String dictCode) {
		set("dict_code", dictCode);
	}

	public java.lang.String getDictCode() {
		return get("dict_code");
	}

	public void setPriority(java.lang.Integer priority) {
		set("priority", priority);
	}

	public java.lang.Integer getPriority() {
		return get("priority");
	}

	public void setAnnotation(java.lang.String annotation) {
		set("annotation", annotation);
	}

	public java.lang.String getAnnotation() {
		return get("annotation");
	}

	public void setAnswer(java.lang.String answer) {
		set("answer", answer);
	}

	public java.lang.String getAnswer() {
		return get("answer");
	}

	public void setIsrequired(java.lang.Integer isrequired) {
		set("isrequired", isrequired);
	}

	public java.lang.Integer getIsrequired() {
		return get("isrequired");
	}

	public void setWeight(java.lang.Integer weight) {
		set("weight", weight);
	}

	public java.lang.Integer getWeight() {
		return get("weight");
	}

	public void setQuestionStatus(java.lang.String questionStatus) {
		set("question_status", questionStatus);
	}

	public java.lang.String getQuestionStatus() {
		return get("question_status");
	}

	public void setSelectNum(java.lang.Integer selectNum) {
		set("select_num", selectNum);
	}

	public java.lang.Integer getSelectNum() {
		return get("select_num");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateUser(java.lang.Integer createUser) {
		set("create_user", createUser);
	}

	public java.lang.Integer getCreateUser() {
		return get("create_user");
	}

	public void setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
	}

	public java.lang.Integer getDeleteFlag() {
		return get("delete_flag");
	}

	public void setCreateUsername(java.lang.String createUsername) {
		set("create_username", createUsername);
	}

	public java.lang.String getCreateUsername() {
		return get("create_username");
	}

	public void setVersionId(java.lang.Integer versionId) {
		set("version_id", versionId);
	}

	public java.lang.Integer getVersionId() {
		return get("version_id");
	}

}
