package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDictionary<M extends BaseDictionary<M>> extends Model<M> implements IBean {

	public void setDictId(java.lang.Integer dictId) {
		set("dict_id", dictId);
	}

	public java.lang.Integer getDictId() {
		return get("dict_id");
	}

	public void setDictCode(java.lang.String dictCode) {
		set("dict_code", dictCode);
	}

	public java.lang.String getDictCode() {
		return get("dict_code");
	}

	public void setDictPcode(java.lang.String dictPcode) {
		set("dict_pcode", dictPcode);
	}

	public java.lang.String getDictPcode() {
		return get("dict_pcode");
	}

	public void setDictPid(java.lang.Integer dictPid) {
		set("dict_pid", dictPid);
	}

	public java.lang.Integer getDictPid() {
		return get("dict_pid");
	}

	public void setDictType(java.lang.String dictType) {
		set("dict_type", dictType);
	}

	public java.lang.String getDictType() {
		return get("dict_type");
	}

	public void setDataType(java.lang.Integer dataType) {
		set("data_type", dataType);
	}

	public java.lang.Integer getDataType() {
		return get("data_type");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setShortName(java.lang.String shortName) {
		set("short_name", shortName);
	}

	public java.lang.String getShortName() {
		return get("short_name");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setValue(java.lang.String value) {
		set("value", value);
	}

	public java.lang.String getValue() {
		return get("value");
	}

	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}

	public java.lang.Integer getSort() {
		return get("sort");
	}

	public void setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
	}

	public java.lang.Integer getDeleteFlag() {
		return get("delete_flag");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
	}

	public java.lang.String getCreateUser() {
		return get("create_user");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
	}

	public java.lang.String getUpdateUser() {
		return get("update_user");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
