package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCity<M extends BaseCity<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCountryId(java.lang.Integer countryId) {
		set("country_id", countryId);
	}

	public java.lang.Integer getCountryId() {
		return get("country_id");
	}

	public void setCountryName(java.lang.String countryName) {
		set("country_name", countryName);
	}

	public java.lang.String getCountryName() {
		return get("country_name");
	}

	public void setCityId(java.lang.String cityId) {
		set("city_id", cityId);
	}

	public java.lang.String getCityId() {
		return get("city_id");
	}

	public void setCityName(java.lang.String cityName) {
		set("city_name", cityName);
	}

	public java.lang.String getCityName() {
		return get("city_name");
	}

	public void setCityEgname(java.lang.String cityEgname) {
		set("city_egname", cityEgname);
	}

	public java.lang.String getCityEgname() {
		return get("city_egname");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setThumbImg(java.lang.String thumbImg) {
		set("thumb_img", thumbImg);
	}

	public java.lang.String getThumbImg() {
		return get("thumb_img");
	}

	public void setBigImg(java.lang.String bigImg) {
		set("big_img", bigImg);
	}

	public java.lang.String getBigImg() {
		return get("big_img");
	}

	public void setIsHot(java.lang.Integer isHot) {
		set("is_hot", isHot);
	}

	public java.lang.Integer getIsHot() {
		return get("is_hot");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateUserid(java.lang.Integer createUserid) {
		set("create_userid", createUserid);
	}

	public java.lang.Integer getCreateUserid() {
		return get("create_userid");
	}

	public void setCreateUsername(java.lang.String createUsername) {
		set("create_username", createUsername);
	}

	public java.lang.String getCreateUsername() {
		return get("create_username");
	}

	public void setModifyTime(java.util.Date modifyTime) {
		set("modify_time", modifyTime);
	}

	public java.util.Date getModifyTime() {
		return get("modify_time");
	}

	public void setModifyUserid(java.lang.Integer modifyUserid) {
		set("modify_userid", modifyUserid);
	}

	public java.lang.Integer getModifyUserid() {
		return get("modify_userid");
	}

	public void setModifyUsername(java.lang.String modifyUsername) {
		set("modify_username", modifyUsername);
	}

	public java.lang.String getModifyUsername() {
		return get("modify_username");
	}

	public void setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
	}

	public java.lang.Integer getDeleteFlag() {
		return get("delete_flag");
	}

	public void setDeleteTime(java.util.Date deleteTime) {
		set("delete_time", deleteTime);
	}

	public java.util.Date getDeleteTime() {
		return get("delete_time");
	}

	public void setDeleteUserid(java.lang.Integer deleteUserid) {
		set("delete_userid", deleteUserid);
	}

	public java.lang.Integer getDeleteUserid() {
		return get("delete_userid");
	}

	public void setDeleteUsername(java.lang.String deleteUsername) {
		set("delete_username", deleteUsername);
	}

	public java.lang.String getDeleteUsername() {
		return get("delete_username");
	}

}
