package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProjectResource<M extends BaseProjectResource<M>> extends Model<M> implements IBean {

	public void setProjectResourceId(java.lang.Integer projectResourceId) {
		set("project_resource_id", projectResourceId);
	}

	public java.lang.Integer getProjectResourceId() {
		return get("project_resource_id");
	}

	public void setProjectId(java.lang.Integer projectId) {
		set("project_id", projectId);
	}

	public java.lang.Integer getProjectId() {
		return get("project_id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
	}

	public java.lang.Integer getDeleteFlag() {
		return get("delete_flag");
	}

	public void setMediaType(java.lang.String mediaType) {
		set("media_type", mediaType);
	}

	public java.lang.String getMediaType() {
		return get("media_type");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setPriority(java.lang.Integer priority) {
		set("priority", priority);
	}

	public java.lang.Integer getPriority() {
		return get("priority");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setSize(java.lang.String size) {
		set("size", size);
	}

	public java.lang.String getSize() {
		return get("size");
	}

}
