package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustSigninfo<M extends BaseCustSigninfo<M>> extends Model<M> implements IBean {

	public void setSignedId(java.lang.Integer signedId) {
		set("signed_id", signedId);
	}

	public java.lang.Integer getSignedId() {
		return get("signed_id");
	}

	public void setCustinfoId(java.lang.Integer custinfoId) {
		set("custinfo_id", custinfoId);
	}

	public java.lang.Integer getCustinfoId() {
		return get("custinfo_id");
	}

	public void setDealNo(java.lang.String dealNo) {
		set("deal_no", dealNo);
	}

	public java.lang.String getDealNo() {
		return get("deal_no");
	}

	public void setCountry(java.lang.String country) {
		set("country", country);
	}

	public java.lang.String getCountry() {
		return get("country");
	}

	public void setProjectId(java.lang.Integer projectId) {
		set("project_id", projectId);
	}

	public java.lang.Integer getProjectId() {
		return get("project_id");
	}

	public void setPartner(java.lang.String partner) {
		set("partner", partner);
	}

	public java.lang.String getPartner() {
		return get("partner");
	}

	public void setServiceLawyer(java.lang.String serviceLawyer) {
		set("service_lawyer", serviceLawyer);
	}

	public java.lang.String getServiceLawyer() {
		return get("service_lawyer");
	}

	public void setServiceFee(java.math.BigDecimal serviceFee) {
		set("service_fee", serviceFee);
	}

	public java.math.BigDecimal getServiceFee() {
		return get("service_fee");
	}

	public void setFee(java.math.BigDecimal fee) {
		set("fee", fee);
	}

	public java.math.BigDecimal getFee() {
		return get("fee");
	}

	public void setPaycode(java.lang.String paycode) {
		set("paycode", paycode);
	}

	public java.lang.String getPaycode() {
		return get("paycode");
	}

	public void setSignDate(java.util.Date signDate) {
		set("sign_date", signDate);
	}

	public java.util.Date getSignDate() {
		return get("sign_date");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setDealPath(java.lang.String dealPath) {
		set("deal_path", dealPath);
	}

	public java.lang.String getDealPath() {
		return get("deal_path");
	}

	public void setResume(java.lang.String resume) {
		set("resume", resume);
	}

	public java.lang.String getResume() {
		return get("resume");
	}

	public void setOperatorId(java.lang.Integer operatorId) {
		set("operator_id", operatorId);
	}

	public java.lang.Integer getOperatorId() {
		return get("operator_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
	}

	public java.lang.Integer getDeleteFlag() {
		return get("delete_flag");
	}

	public void setOtherApplicant(java.lang.String otherApplicant) {
		set("other_applicant", otherApplicant);
	}

	public java.lang.String getOtherApplicant() {
		return get("other_applicant");
	}

	public void setAdviser(java.lang.String adviser) {
		set("adviser", adviser);
	}

	public java.lang.String getAdviser() {
		return get("adviser");
	}

}
