package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTopicSetting<M extends BaseTopicSetting<M>> extends Model<M> implements IBean {

	public void setSettingId(java.lang.Integer settingId) {
		set("setting_id", settingId);
	}

	public java.lang.Integer getSettingId() {
		return get("setting_id");
	}

	public void setWechatNumber(java.lang.Integer wechatNumber) {
		set("wechat_number", wechatNumber);
	}

	public java.lang.Integer getWechatNumber() {
		return get("wechat_number");
	}

	public void setWechatFrequency(java.lang.Integer wechatFrequency) {
		set("wechat_frequency", wechatFrequency);
	}

	public java.lang.Integer getWechatFrequency() {
		return get("wechat_frequency");
	}

	public void setOfficialNumber(java.lang.Integer officialNumber) {
		set("official_number", officialNumber);
	}

	public java.lang.Integer getOfficialNumber() {
		return get("official_number");
	}

	public void setOfficialFrequency(java.lang.Integer officialFrequency) {
		set("official_frequency", officialFrequency);
	}

	public java.lang.Integer getOfficialFrequency() {
		return get("official_frequency");
	}

}
