package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustinfo<M extends BaseCustinfo<M>> extends Model<M> implements IBean {

	public void setCustinfoId(java.lang.Integer custinfoId) {
		set("custinfo_id", custinfoId);
	}

	public java.lang.Integer getCustinfoId() {
		return get("custinfo_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setGender(java.lang.String gender) {
		set("gender", gender);
	}

	public java.lang.String getGender() {
		return get("gender");
	}

	public void setPhoneNum(java.lang.String phoneNum) {
		set("phone_num", phoneNum);
	}

	public java.lang.String getPhoneNum() {
		return get("phone_num");
	}

	public void setCustType(java.lang.String custType) {
		set("cust_type", custType);
	}

	public java.lang.String getCustType() {
		return get("cust_type");
	}

	public void setCustSource(java.lang.String custSource) {
		set("cust_source", custSource);
	}

	public java.lang.String getCustSource() {
		return get("cust_source");
	}

	public void setArea(java.lang.String area) {
		set("area", area);
	}

	public java.lang.String getArea() {
		return get("area");
	}

	public void setRecommender(java.lang.String recommender) {
		set("recommender", recommender);
	}

	public java.lang.String getRecommender() {
		return get("recommender");
	}

	public void setAdviser(java.lang.String adviser) {
		set("adviser", adviser);
	}

	public java.lang.String getAdviser() {
		return get("adviser");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
	}

	public java.lang.String getCreateUser() {
		return get("create_user");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
	}

	public java.lang.String getUpdateUser() {
		return get("update_user");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setCustStatus(java.lang.String custStatus) {
		set("cust_status", custStatus);
	}

	public java.lang.String getCustStatus() {
		return get("cust_status");
	}

	public void setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
	}

	public java.lang.Integer getDeleteFlag() {
		return get("delete_flag");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setOpenId(java.lang.String openId) {
		set("open_id", openId);
	}

	public java.lang.String getOpenId() {
		return get("open_id");
	}

	public void setWxName(java.lang.String wxName) {
		set("wx_name", wxName);
	}

	public java.lang.String getWxName() {
		return get("wx_name");
	}

	public void setIsLogin(java.lang.Integer isLogin) {
		set("is_login", isLogin);
	}

	public java.lang.Integer getIsLogin() {
		return get("is_login");
	}

	public void setBalance(java.lang.String balance) {
		set("balance", balance);
	}

	public java.lang.String getBalance() {
		return get("balance");
	}

	public void setLoginName(java.lang.String loginName) {
		set("login_name", loginName);
	}

	public java.lang.String getLoginName() {
		return get("login_name");
	}

	public void setNickName(java.lang.String nickName) {
		set("nick_name", nickName);
	}

	public java.lang.String getNickName() {
		return get("nick_name");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
	}

	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public void setQq(java.lang.String qq) {
		set("qq", qq);
	}

	public java.lang.String getQq() {
		return get("qq");
	}

	public void setWx(java.lang.String wx) {
		set("wx", wx);
	}

	public java.lang.String getWx() {
		return get("wx");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setNamePinyin(java.lang.String namePinyin) {
		set("name_pinyin", namePinyin);
	}

	public java.lang.String getNamePinyin() {
		return get("name_pinyin");
	}

	public void setNameEnglish(java.lang.String nameEnglish) {
		set("name_english", nameEnglish);
	}

	public java.lang.String getNameEnglish() {
		return get("name_english");
	}

	public void setEducation(java.lang.String education) {
		set("education", education);
	}

	public java.lang.String getEducation() {
		return get("education");
	}

	public void setLastTime(java.util.Date lastTime) {
		set("last_time", lastTime);
	}

	public java.util.Date getLastTime() {
		return get("last_time");
	}

	public void setLastIp(java.lang.String lastIp) {
		set("last_ip", lastIp);
	}

	public java.lang.String getLastIp() {
		return get("last_ip");
	}

	public void setOrgId(java.lang.String orgId) {
		set("org_id", orgId);
	}

	public java.lang.String getOrgId() {
		return get("org_id");
	}

	public void setDirection(java.lang.Integer direction) {
		set("direction", direction);
	}

	public java.lang.Integer getDirection() {
		return get("direction");
	}

	public void setIsChanged(java.lang.Integer isChanged) {
		set("is_changed", isChanged);
	}

	public java.lang.Integer getIsChanged() {
		return get("is_changed");
	}

	public void setProvince(java.lang.String province) {
		set("province", province);
	}

	public java.lang.String getProvince() {
		return get("province");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}

	public java.lang.String getCity() {
		return get("city");
	}

	public void setContact(java.lang.String contact) {
		set("contact", contact);
	}

	public java.lang.String getContact() {
		return get("contact");
	}

	public void setHeadImg(java.lang.String headImg) {
		set("head_img", headImg);
	}

	public java.lang.String getHeadImg() {
		return get("head_img");
	}

	public void setProxy(java.lang.Integer proxy) {
		set("proxy", proxy);
	}

	public java.lang.Integer getProxy() {
		return get("proxy");
	}

	public void setProxyPid(java.lang.Integer proxyPid) {
		set("proxy_pid", proxyPid);
	}

	public java.lang.Integer getProxyPid() {
		return get("proxy_pid");
	}

	public void setProxyLevel(java.lang.String proxyLevel) {
		set("proxy_level", proxyLevel);
	}

	public java.lang.String getProxyLevel() {
		return get("proxy_level");
	}

	public void setProxyStatus(java.lang.String proxyStatus) {
		set("proxy_status", proxyStatus);
	}

	public java.lang.String getProxyStatus() {
		return get("proxy_status");
	}

	public void setAuditStatus(java.lang.String auditStatus) {
		set("audit_status", auditStatus);
	}

	public java.lang.String getAuditStatus() {
		return get("audit_status");
	}

	public void setPassedTime(java.util.Date passedTime) {
		set("passed_time", passedTime);
	}

	public java.util.Date getPassedTime() {
		return get("passed_time");
	}

	public void setBindProxyTime(java.util.Date bindProxyTime) {
		set("bind_proxy_time", bindProxyTime);
	}

	public java.util.Date getBindProxyTime() {
		return get("bind_proxy_time");
	}

	public void setMemberStatus(java.lang.String memberStatus) {
		set("member_status", memberStatus);
	}

	public java.lang.String getMemberStatus() {
		return get("member_status");
	}

}
