package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoleStation<M extends BaseRoleStation<M>> extends Model<M> implements IBean {

	public void setStationId(java.lang.Integer stationId) {
		set("station_id", stationId);
	}

	public java.lang.Integer getStationId() {
		return get("station_id");
	}

	public void setRoleId(java.lang.Integer roleId) {
		set("role_id", roleId);
	}

	public java.lang.Integer getRoleId() {
		return get("role_id");
	}

}
