package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAboutNav<M extends BaseAboutNav<M>> extends Model<M> implements IBean {

	public void setOanId(java.lang.Integer oanId) {
		set("oan_id", oanId);
	}

	public java.lang.Integer getOanId() {
		return get("oan_id");
	}

	public void setNavName(java.lang.String navName) {
		set("nav_name", navName);
	}

	public java.lang.String getNavName() {
		return get("nav_name");
	}

	public void setNavUrl(java.lang.String navUrl) {
		set("nav_url", navUrl);
	}

	public java.lang.String getNavUrl() {
		return get("nav_url");
	}

	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}

	public java.lang.Integer getSort() {
		return get("sort");
	}

	public void setEditTime(java.util.Date editTime) {
		set("edit_time", editTime);
	}

	public java.util.Date getEditTime() {
		return get("edit_time");
	}

	public void setEditor(java.lang.String editor) {
		set("editor", editor);
	}

	public java.lang.String getEditor() {
		return get("editor");
	}

	public void setEditEnable(java.lang.Integer editEnable) {
		set("edit_enable", editEnable);
	}

	public java.lang.Integer getEditEnable() {
		return get("edit_enable");
	}

}
