package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProfessionalTeam<M extends BaseProfessionalTeam<M>> extends Model<M> implements IBean {

	public void setTeamId(java.lang.Integer teamId) {
		set("team_id", teamId);
	}

	public java.lang.Integer getTeamId() {
		return get("team_id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
	}

	public java.lang.Integer getDeleteFlag() {
		return get("delete_flag");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
	}

	public java.lang.String getCreateUser() {
		return get("create_user");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
	}

	public java.lang.String getUpdateUser() {
		return get("update_user");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setExpertCountry(java.lang.String expertCountry) {
		set("expert_country", expertCountry);
	}

	public java.lang.String getExpertCountry() {
		return get("expert_country");
	}

	public void setIndexShow(java.lang.Integer indexShow) {
		set("index_show", indexShow);
	}

	public java.lang.Integer getIndexShow() {
		return get("index_show");
	}

	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}

	public java.lang.Integer getSort() {
		return get("sort");
	}
	
	public void setReleaseMark(java.lang.String releaseMark) {
		set("release_mark", releaseMark);
	}

	public java.lang.String getReleaseMark() {
		return get("release_mark");
	}

	public void setTeamType(java.lang.String teamType) {
		set("team_type", teamType);
	}

	public java.lang.String getTeamType() {
		return get("team_type");
	}

	public void setVideo(java.lang.String video) {
		set("video", video);
	}

	public java.lang.String getVideo() {
		return get("video");
	}
}
