package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAddressCountry<M extends BaseAddressCountry<M>> extends Model<M> implements IBean {

	public void setCountryId(java.lang.String CountryId) {
		set("CountryId", CountryId);
	}

	public java.lang.String getCountryId() {
		return get("CountryId");
	}

	public void setCountryName(java.lang.String CountryName) {
		set("CountryName", CountryName);
	}

	public java.lang.String getCountryName() {
		return get("CountryName");
	}

	public void setCountryCode(java.lang.String CountryCode) {
		set("CountryCode", CountryCode);
	}

	public java.lang.String getCountryCode() {
		return get("CountryCode");
	}

	public void setQuickCode(java.lang.String QuickCode) {
		set("QuickCode", QuickCode);
	}

	public java.lang.String getQuickCode() {
		return get("QuickCode");
	}

	public void setDescription(java.lang.String Description) {
		set("Description", Description);
	}

	public java.lang.String getDescription() {
		return get("Description");
	}

	public void setVersionNumber(java.lang.Integer VersionNumber) {
		set("VersionNumber", VersionNumber);
	}

	public java.lang.Integer getVersionNumber() {
		return get("VersionNumber");
	}

	public void setEnName(java.lang.String EnName) {
		set("EnName", EnName);
	}

	public java.lang.String getEnName() {
		return get("EnName");
	}

	public void setFirstCode(java.lang.String FirstCode) {
		set("FirstCode", FirstCode);
	}

	public java.lang.String getFirstCode() {
		return get("FirstCode");
	}

	public void setIntroduce(java.lang.String Introduce) {
		set("Introduce", Introduce);
	}

	public java.lang.String getIntroduce() {
		return get("Introduce");
	}

	public void setLiveRequirementLevel(java.lang.String liveRequirementLevel) {
		set("LIVE_REQUIREMENT_LEVEL", liveRequirementLevel);
	}

	public java.lang.String getLiveRequirementLevel() {
		return get("LIVE_REQUIREMENT_LEVEL");
	}

	public void setSocialWelfareLevel(java.lang.String socialWelfareLevel) {
		set("SOCIAL_WELFARE_LEVEL", socialWelfareLevel);
	}

	public java.lang.String getSocialWelfareLevel() {
		return get("SOCIAL_WELFARE_LEVEL");
	}

	public void setEducationalStandardsLevel(java.lang.String educationalStandardsLevel) {
		set("EDUCATIONAL_STANDARDS_LEVEL", educationalStandardsLevel);
	}

	public java.lang.String getEducationalStandardsLevel() {
		return get("EDUCATIONAL_STANDARDS_LEVEL");
	}

	public void setInvestmentLevel(java.lang.String investmentLevel) {
		set("INVESTMENT_LEVEL", investmentLevel);
	}

	public java.lang.String getInvestmentLevel() {
		return get("INVESTMENT_LEVEL");
	}

	public void setEmploymentEnvironmentLevel(java.lang.String employmentEnvironmentLevel) {
		set("EMPLOYMENT_ENVIRONMENT_LEVEL", employmentEnvironmentLevel);
	}

	public java.lang.String getEmploymentEnvironmentLevel() {
		return get("EMPLOYMENT_ENVIRONMENT_LEVEL");
	}

	public void setIconImg(java.lang.String iconImg) {
		set("ICON_IMG", iconImg);
	}

	public java.lang.String getIconImg() {
		return get("ICON_IMG");
	}

	public void setCountryImg(java.lang.String countryImg) {
		set("COUNTRY_IMG", countryImg);
	}

	public java.lang.String getCountryImg() {
		return get("COUNTRY_IMG");
	}

	public void setLiveRequirement(java.lang.String liveRequirement) {
		set("LIVE_REQUIREMENT", liveRequirement);
	}

	public java.lang.String getLiveRequirement() {
		return get("LIVE_REQUIREMENT");
	}

	public void setSocialWelfare(java.lang.String socialWelfare) {
		set("SOCIAL_WELFARE", socialWelfare);
	}

	public java.lang.String getSocialWelfare() {
		return get("SOCIAL_WELFARE");
	}

	public void setEducationalStandards(java.lang.String educationalStandards) {
		set("EDUCATIONAL_STANDARDS", educationalStandards);
	}

	public java.lang.String getEducationalStandards() {
		return get("EDUCATIONAL_STANDARDS");
	}

	public void setINVESTMENT(java.lang.String INVESTMENT) {
		set("INVESTMENT", INVESTMENT);
	}

	public java.lang.String getINVESTMENT() {
		return get("INVESTMENT");
	}

	public void setEmploymentEnvironment(java.lang.String employmentEnvironment) {
		set("EMPLOYMENT_ENVIRONMENT", employmentEnvironment);
	}

	public java.lang.String getEmploymentEnvironment() {
		return get("EMPLOYMENT_ENVIRONMENT");
	}

	public void setNATIONALITY(java.lang.String NATIONALITY) {
		set("NATIONALITY", NATIONALITY);
	}

	public java.lang.String getNATIONALITY() {
		return get("NATIONALITY");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

	public void setUpdataTime(java.util.Date updataTime) {
		set("UPDATA_TIME", updataTime);
	}

	public java.util.Date getUpdataTime() {
		return get("UPDATA_TIME");
	}

}
