package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSection<M extends BaseSection<M>> extends Model<M> implements IBean {

	public void setSectionId(java.lang.Integer sectionId) {
		set("section_id", sectionId);
	}

	public java.lang.Integer getSectionId() {
		return get("section_id");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}

	public java.lang.String getCode() {
		return get("code");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setPname(java.lang.String pname) {
		set("pname", pname);
	}

	public java.lang.String getPname() {
		return get("pname");
	}

	public void setPcode(java.lang.String pcode) {
		set("pcode", pcode);
	}

	public java.lang.String getPcode() {
		return get("pcode");
	}

	public void setSectionType(java.lang.String sectionType) {
		set("section_type", sectionType);
	}

	public java.lang.String getSectionType() {
		return get("section_type");
	}

	public void setStaticDir(java.lang.String staticDir) {
		set("static_dir", staticDir);
	}

	public java.lang.String getStaticDir() {
		return get("static_dir");
	}

	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}

	public java.lang.Integer getSort() {
		return get("sort");
	}

	public void setSectionImg(java.lang.String sectionImg) {
		set("section_img", sectionImg);
	}

	public java.lang.String getSectionImg() {
		return get("section_img");
	}

	public void setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
	}

	public java.lang.Integer getDeleteFlag() {
		return get("delete_flag");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateUserid(java.lang.Integer createUserid) {
		set("create_userid", createUserid);
	}

	public java.lang.Integer getCreateUserid() {
		return get("create_userid");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
	}

	public java.lang.String getCreateUser() {
		return get("create_user");
	}

	public void setEditTime(java.util.Date editTime) {
		set("edit_time", editTime);
	}

	public java.util.Date getEditTime() {
		return get("edit_time");
	}

	public void setEditUserid(java.lang.Integer editUserid) {
		set("edit_userid", editUserid);
	}

	public java.lang.Integer getEditUserid() {
		return get("edit_userid");
	}

	public void setEditUser(java.lang.String editUser) {
		set("edit_user", editUser);
	}

	public java.lang.String getEditUser() {
		return get("edit_user");
	}

	public void setImgSizeGw(java.lang.String imgSizeGw) {
		set("img_size_gw", imgSizeGw);
	}

	public java.lang.String getImgSizeGw() {
		return get("img_size_gw");
	}

	public void setIndexEnable(java.lang.Integer indexEnable) {
		set("index_enable", indexEnable);
	}

	public java.lang.Integer getIndexEnable() {
		return get("index_enable");
	}

}
