package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEstimateQuestionVersion<M extends BaseEstimateQuestionVersion<M>> extends Model<M> implements IBean {

	public void setVersionId(java.lang.Integer versionId) {
		set("version_id", versionId);
	}

	public java.lang.Integer getVersionId() {
		return get("version_id");
	}

	public void setVersionNo(java.lang.String versionNo) {
		set("version_no", versionNo);
	}

	public java.lang.String getVersionNo() {
		return get("version_no");
	}

	public void setCreateUserid(java.lang.Integer createUserid) {
		set("create_userid", createUserid);
	}

	public java.lang.Integer getCreateUserid() {
		return get("create_userid");
	}

	public void setCreateUsername(java.lang.String createUsername) {
		set("create_username", createUsername);
	}

	public java.lang.String getCreateUsername() {
		return get("create_username");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
	}

	public java.lang.Integer getDeleteFlag() {
		return get("delete_flag");
	}

	public void setPublishTime(java.util.Date publishTime) {
		set("publish_time", publishTime);
	}

	public java.util.Date getPublishTime() {
		return get("publish_time");
	}

	public void setPublishUserid(java.lang.Integer publishUserid) {
		set("publish_userid", publishUserid);
	}

	public java.lang.Integer getPublishUserid() {
		return get("publish_userid");
	}

	public void setPublishUsername(java.lang.String publishUsername) {
		set("publish_username", publishUsername);
	}

	public java.lang.String getPublishUsername() {
		return get("publish_username");
	}

}
