package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseResource<M extends BaseResource<M>> extends Model<M> implements IBean {

	public void setResId(java.lang.Integer resId) {
		set("res_id", resId);
	}

	public java.lang.Integer getResId() {
		return get("res_id");
	}

	public void setSysId(java.lang.Integer sysId) {
		set("sys_id", sysId);
	}

	public java.lang.Integer getSysId() {
		return get("sys_id");
	}

	public void setResCode(java.lang.String resCode) {
		set("res_code", resCode);
	}

	public java.lang.String getResCode() {
		return get("res_code");
	}

	public void setResPcode(java.lang.String resPcode) {
		set("res_pcode", resPcode);
	}

	public java.lang.String getResPcode() {
		return get("res_pcode");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setValidateType(java.lang.String validateType) {
		set("validate_type", validateType);
	}

	public java.lang.String getValidateType() {
		return get("validate_type");
	}

	public void setResType(java.lang.String resType) {
		set("res_type", resType);
	}

	public java.lang.String getResType() {
		return get("res_type");
	}

	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}

	public java.lang.String getIcon() {
		return get("icon");
	}

	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}

	public java.lang.Integer getSort() {
		return get("sort");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
	}

	public java.lang.Integer getDeleteFlag() {
		return get("delete_flag");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
	}

	public java.lang.String getCreateUser() {
		return get("create_user");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
	}

	public java.lang.String getUpdateUser() {
		return get("update_user");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
