package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustinfoReceive<M extends BaseCustinfoReceive<M>> extends Model<M> implements IBean {

	public void setCustinfoReceiveId(java.lang.Integer custinfoReceiveId) {
		set("custinfo_receive_id", custinfoReceiveId);
	}

	public java.lang.Integer getCustinfoReceiveId() {
		return get("custinfo_receive_id");
	}

	public void setCustinfoId(java.lang.Integer custinfoId) {
		set("custinfo_id", custinfoId);
	}

	public java.lang.Integer getCustinfoId() {
		return get("custinfo_id");
	}

	public void setRecName(java.lang.String recName) {
		set("rec_name", recName);
	}

	public java.lang.String getRecName() {
		return get("rec_name");
	}

	public void setRecProvince(java.lang.String recProvince) {
		set("rec_province", recProvince);
	}

	public java.lang.String getRecProvince() {
		return get("rec_province");
	}

	public void setRecCity(java.lang.String recCity) {
		set("rec_city", recCity);
	}

	public java.lang.String getRecCity() {
		return get("rec_city");
	}

	public void setRecPhone(java.lang.String recPhone) {
		set("rec_phone", recPhone);
	}

	public java.lang.String getRecPhone() {
		return get("rec_phone");
	}

	public void setRecAddress(java.lang.String recAddress) {
		set("rec_address", recAddress);
	}

	public java.lang.String getRecAddress() {
		return get("rec_address");
	}

	public void setPostCode(java.lang.Integer postCode) {
		set("post_code", postCode);
	}

	public java.lang.Integer getPostCode() {
		return get("post_code");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setIsUse(java.lang.Integer isUse) {
		set("is_use", isUse);
	}

	public java.lang.Integer getIsUse() {
		return get("is_use");
	}

	public void setIsDefault(java.lang.Integer isDefault) {
		set("is_default", isDefault);
	}

	public java.lang.Integer getIsDefault() {
		return get("is_default");
	}

}
