package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseInformationImg<M extends BaseInformationImg<M>> extends Model<M> implements IBean {

	public void setInfoId(java.lang.Integer infoId) {
		set("info_id", infoId);
	}

	public java.lang.Integer getInfoId() {
		return get("info_id");
	}

	public void setSectionId(java.lang.String sectionId) {
		set("section_id", sectionId);
	}

	public java.lang.String getSectionId() {
		return get("section_id");
	}

	public void setSectionName(java.lang.String sectionName) {
		set("section_name", sectionName);
	}

	public java.lang.String getSectionName() {
		return get("section_name");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setCountry(java.lang.String country) {
		set("country", country);
	}

	public java.lang.String getCountry() {
		return get("country");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}

	public java.lang.String getCity() {
		return get("city");
	}

	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}

	public java.lang.Integer getSort() {
		return get("sort");
	}

	public void setThumbImg(java.lang.String thumbImg) {
		set("thumb_img", thumbImg);
	}

	public java.lang.String getThumbImg() {
		return get("thumb_img");
	}

	public void setInfoImg(java.lang.String infoImg) {
		set("info_img", infoImg);
	}

	public java.lang.String getInfoImg() {
		return get("info_img");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setVedioUrl(java.lang.String vedioUrl) {
		set("vedio_url", vedioUrl);
	}

	public java.lang.String getVedioUrl() {
		return get("vedio_url");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
	}

	public java.lang.Integer getDeleteFlag() {
		return get("delete_flag");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateUserid(java.lang.Integer createUserid) {
		set("create_userid", createUserid);
	}

	public java.lang.Integer getCreateUserid() {
		return get("create_userid");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
	}

	public java.lang.String getCreateUser() {
		return get("create_user");
	}

	public void setEditTime(java.util.Date editTime) {
		set("edit_time", editTime);
	}

	public java.util.Date getEditTime() {
		return get("edit_time");
	}

	public void setEditUserid(java.lang.Integer editUserid) {
		set("edit_userid", editUserid);
	}

	public java.lang.Integer getEditUserid() {
		return get("edit_userid");
	}

	public void setEditUser(java.lang.String editUser) {
		set("edit_user", editUser);
	}

	public java.lang.String getEditUser() {
		return get("edit_user");
	}

	public void setDeleteTime(java.util.Date deleteTime) {
		set("delete_time", deleteTime);
	}

	public java.util.Date getDeleteTime() {
		return get("delete_time");
	}

	public void setDeleteUserid(java.lang.Integer deleteUserid) {
		set("delete_userid", deleteUserid);
	}

	public java.lang.Integer getDeleteUserid() {
		return get("delete_userid");
	}

	public void setDeleteUser(java.lang.String deleteUser) {
		set("delete_user", deleteUser);
	}

	public java.lang.String getDeleteUser() {
		return get("delete_user");
	}

	public void setPublishTime(java.util.Date publishTime) {
		set("publish_time", publishTime);
	}

	public java.util.Date getPublishTime() {
		return get("publish_time");
	}

	public void setPublishUserid(java.lang.Integer publishUserid) {
		set("publish_userid", publishUserid);
	}

	public java.lang.Integer getPublishUserid() {
		return get("publish_userid");
	}

	public void setPublishUser(java.lang.String publishUser) {
		set("publish_user", publishUser);
	}

	public java.lang.String getPublishUser() {
		return get("publish_user");
	}

	public void setClickCount(java.lang.Integer clickCount) {
		set("click_count", clickCount);
	}

	public java.lang.Integer getClickCount() {
		return get("click_count");
	}

}
