package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrgnizationWebsys<M extends BaseOrgnizationWebsys<M>> extends Model<M> implements IBean {

	public void setOrgId(java.lang.Integer orgId) {
		set("org_id", orgId);
	}

	public java.lang.Integer getOrgId() {
		return get("org_id");
	}

	public void setSysId(java.lang.Integer sysId) {
		set("sys_id", sysId);
	}

	public java.lang.Integer getSysId() {
		return get("sys_id");
	}

}
