package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNavMenu<M extends BaseNavMenu<M>> extends Model<M> implements IBean {

	public void setNavMenuId(java.lang.Integer navMenuId) {
		set("nav_menu_id", navMenuId);
	}

	public java.lang.Integer getNavMenuId() {
		return get("nav_menu_id");
	}

	public void setMenuName(java.lang.String menuName) {
		set("menu_name", menuName);
	}

	public java.lang.String getMenuName() {
		return get("menu_name");
	}

	public void setMenuUrl(java.lang.String menuUrl) {
		set("menu_url", menuUrl);
	}

	public java.lang.String getMenuUrl() {
		return get("menu_url");
	}

	public void setOpenMode(java.lang.String openMode) {
		set("open_mode", openMode);
	}

	public java.lang.String getOpenMode() {
		return get("open_mode");
	}

	public void setMenuStatus(java.lang.String menuStatus) {
		set("menu_status", menuStatus);
	}

	public java.lang.String getMenuStatus() {
		return get("menu_status");
	}

	public void setMenuLevel(java.lang.Integer menuLevel) {
		set("menu_level", menuLevel);
	}

	public java.lang.Integer getMenuLevel() {
		return get("menu_level");
	}

	public void setMenuPid(java.lang.Integer menuPid) {
		set("menu_pid", menuPid);
	}

	public java.lang.Integer getMenuPid() {
		return get("menu_pid");
	}

	public void setMenuType(java.lang.String menuType) {
		set("menu_type", menuType);
	}

	public java.lang.String getMenuType() {
		return get("menu_type");
	}

	public void setDictCode(java.lang.String dictCode) {
		set("dict_code", dictCode);
	}

	public java.lang.String getDictCode() {
		return get("dict_code");
	}

	public void setPriority(java.lang.Integer priority) {
		set("priority", priority);
	}

	public java.lang.Integer getPriority() {
		return get("priority");
	}

	public void setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
	}

	public java.lang.Integer getDeleteFlag() {
		return get("delete_flag");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
