package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLiveMessage<M extends BaseLiveMessage<M>> extends Model<M> implements IBean {

	public void setMessageId(java.lang.Integer messageId) {
		set("message_id", messageId);
	}

	public java.lang.Integer getMessageId() {
		return get("message_id");
	}

	public void setCustinfoId(java.lang.Integer custinfoId) {
		set("custinfo_id", custinfoId);
	}

	public java.lang.Integer getCustinfoId() {
		return get("custinfo_id");
	}

	public void setLiveId(java.lang.Integer liveId) {
		set("live_id", liveId);
	}

	public java.lang.Integer getLiveId() {
		return get("live_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
	}

	public java.lang.Integer getDeleteFlag() {
		return get("delete_flag");
	}

	public void setContents(java.lang.String contents) {
		set("contents", contents);
	}

	public java.lang.String getContents() {
		return get("contents");
	}

}
