package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxEstimateQuestion<M extends BaseWxEstimateQuestion<M>> extends Model<M> implements IBean {

	public void setEstimateQuestionId(java.lang.Integer estimateQuestionId) {
		set("estimate_question_id", estimateQuestionId);
	}

	public java.lang.Integer getEstimateQuestionId() {
		return get("estimate_question_id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setDictCode(java.lang.String dictCode) {
		set("dict_code", dictCode);
	}

	public java.lang.String getDictCode() {
		return get("dict_code");
	}

	public void setPriority(java.lang.Integer priority) {
		set("priority", priority);
	}

	public java.lang.Integer getPriority() {
		return get("priority");
	}

	public void setAnnotation(java.lang.String annotation) {
		set("annotation", annotation);
	}

	public java.lang.String getAnnotation() {
		return get("annotation");
	}

	public void setAnswer(java.lang.String answer) {
		set("answer", answer);
	}

	public java.lang.String getAnswer() {
		return get("answer");
	}

	public void setIsrequired(java.lang.String isrequired) {
		set("isrequired", isrequired);
	}

	public java.lang.String getIsrequired() {
		return get("isrequired");
	}

	public void setWeight(java.lang.Integer weight) {
		set("weight", weight);
	}

	public java.lang.Integer getWeight() {
		return get("weight");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
	}

	public java.lang.String getCreateUser() {
		return get("create_user");
	}

}
