package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSigninfoAnnex<M extends BaseSigninfoAnnex<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setSignedId(java.lang.Integer signedId) {
		set("signed_id", signedId);
	}

	public java.lang.Integer getSignedId() {
		return get("signed_id");
	}

	public void setCustinfoId(java.lang.Integer custinfoId) {
		set("custinfo_id", custinfoId);
	}

	public java.lang.Integer getCustinfoId() {
		return get("custinfo_id");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setFilepath(java.lang.String filepath) {
		set("filepath", filepath);
	}

	public java.lang.String getFilepath() {
		return get("filepath");
	}

	public void setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
	}

	public java.lang.Integer getDeleteFlag() {
		return get("delete_flag");
	}

	public void setAdviser(java.lang.String adviser) {
		set("adviser", adviser);
	}

	public java.lang.String getAdviser() {
		return get("adviser");
	}

}
