package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAddressCity<M extends BaseAddressCity<M>> extends Model<M> implements IBean {

	public void setCityId(java.lang.String CityId) {
		set("CityId", CityId);
	}

	public java.lang.String getCityId() {
		return get("CityId");
	}

	public void setCountryId(java.lang.String CountryId) {
		set("CountryId", CountryId);
	}

	public java.lang.String getCountryId() {
		return get("CountryId");
	}

	public void setProvinceId(java.lang.String ProvinceId) {
		set("ProvinceId", ProvinceId);
	}

	public java.lang.String getProvinceId() {
		return get("ProvinceId");
	}

	public void setCityName(java.lang.String CityName) {
		set("CityName", CityName);
	}

	public java.lang.String getCityName() {
		return get("CityName");
	}

	public void setAreaCode(java.lang.String AreaCode) {
		set("AreaCode", AreaCode);
	}

	public java.lang.String getAreaCode() {
		return get("AreaCode");
	}

	public void setPostalCode(java.lang.String PostalCode) {
		set("PostalCode", PostalCode);
	}

	public java.lang.String getPostalCode() {
		return get("PostalCode");
	}

	public void setQuickCode(java.lang.String QuickCode) {
		set("QuickCode", QuickCode);
	}

	public java.lang.String getQuickCode() {
		return get("QuickCode");
	}

	public void setDescription(java.lang.String Description) {
		set("Description", Description);
	}

	public java.lang.String getDescription() {
		return get("Description");
	}

	public void setVersionNumber(java.lang.Integer VersionNumber) {
		set("VersionNumber", VersionNumber);
	}

	public java.lang.Integer getVersionNumber() {
		return get("VersionNumber");
	}

	public void setFirstCode(java.lang.String FirstCode) {
		set("FirstCode", FirstCode);
	}

	public java.lang.String getFirstCode() {
		return get("FirstCode");
	}

}
