package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBusinessCooperation<M extends BaseBusinessCooperation<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setApplicantName(java.lang.String applicantName) {
		set("applicant_name", applicantName);
	}

	public java.lang.String getApplicantName() {
		return get("applicant_name");
	}

	public void setApplicantPhone(java.lang.String applicantPhone) {
		set("applicant_phone", applicantPhone);
	}

	public java.lang.String getApplicantPhone() {
		return get("applicant_phone");
	}

	public void setApplicantProvince(java.lang.String applicantProvince) {
		set("applicant_province", applicantProvince);
	}

	public java.lang.String getApplicantProvince() {
		return get("applicant_province");
	}

	public void setApplicantCity(java.lang.String applicantCity) {
		set("applicant_city", applicantCity);
	}

	public java.lang.String getApplicantCity() {
		return get("applicant_city");
	}

	public void setCooperationMode(java.lang.String cooperationMode) {
		set("cooperation_mode", cooperationMode);
	}

	public java.lang.String getCooperationMode() {
		return get("cooperation_mode");
	}

	public void setSubmitTime(java.util.Date submitTime) {
		set("submit_time", submitTime);
	}

	public java.util.Date getSubmitTime() {
		return get("submit_time");
	}

	public void setSubmitUser(java.lang.String submitUser) {
		set("submit_user", submitUser);
	}

	public java.lang.String getSubmitUser() {
		return get("submit_user");
	}

	public void setNegotiationStatus(java.lang.String negotiationStatus) {
		set("negotiation_status", negotiationStatus);
	}

	public java.lang.String getNegotiationStatus() {
		return get("negotiation_status");
	}

	public void setTreatmentStatus(java.lang.String treatmentStatus) {
		set("treatment_status", treatmentStatus);
	}

	public java.lang.String getTreatmentStatus() {
		return get("treatment_status");
	}

	public void setTreatmentResult(java.lang.String treatmentResult) {
		set("treatment_result", treatmentResult);
	}

	public java.lang.String getTreatmentResult() {
		return get("treatment_result");
	}

	public void setTreatmentExplain(java.lang.String treatmentExplain) {
		set("treatment_explain", treatmentExplain);
	}

	public java.lang.String getTreatmentExplain() {
		return get("treatment_explain");
	}

	public void setTreatmentTime(java.util.Date treatmentTime) {
		set("treatment_time", treatmentTime);
	}

	public java.util.Date getTreatmentTime() {
		return get("treatment_time");
	}

	public void setTreatmentOperator(java.lang.String treatmentOperator) {
		set("treatment_operator", treatmentOperator);
	}

	public java.lang.String getTreatmentOperator() {
		return get("treatment_operator");
	}

}