package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProjectMaterial<M extends BaseProjectMaterial<M>> extends Model<M> implements IBean {

	public void setProjectMaterialId(java.lang.Integer projectMaterialId) {
		set("project_material_id", projectMaterialId);
	}

	public java.lang.Integer getProjectMaterialId() {
		return get("project_material_id");
	}

	public void setProjectId(java.lang.Integer projectId) {
		set("project_id", projectId);
	}

	public java.lang.Integer getProjectId() {
		return get("project_id");
	}

	public void setProjectApplyProcessId(java.lang.Integer projectApplyProcessId) {
		set("project_apply_process_id", projectApplyProcessId);
	}

	public java.lang.Integer getProjectApplyProcessId() {
		return get("project_apply_process_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setPriority(java.lang.Integer priority) {
		set("priority", priority);
	}

	public java.lang.Integer getPriority() {
		return get("priority");
	}

	public void setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
	}

	public java.lang.Integer getDeleteFlag() {
		return get("delete_flag");
	}

	public void setSwatchUrl(java.lang.String swatchUrl) {
		set("swatch_url", swatchUrl);
	}

	public java.lang.String getSwatchUrl() {
		return get("swatch_url");
	}

	public void setSwatchName(java.lang.String swatchName) {
		set("swatch_name", swatchName);
	}

	public java.lang.String getSwatchName() {
		return get("swatch_name");
	}

	public void setMaterialType(java.lang.String materialType) {
		set("material_type", materialType);
	}

	public java.lang.String getMaterialType() {
		return get("material_type");
	}

}
