package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLiveApplication<M extends BaseLiveApplication<M>> extends Model<M> implements IBean {

	public void setApplicationId(java.lang.Integer applicationId) {
		set("application_id", applicationId);
	}

	public java.lang.Integer getApplicationId() {
		return get("application_id");
	}

	public void setLiveId(java.lang.Integer liveId) {
		set("live_id", liveId);
	}

	public java.lang.Integer getLiveId() {
		return get("live_id");
	}

	public void setCustinfoId(java.lang.Integer custinfoId) {
		set("custinfo_id", custinfoId);
	}

	public java.lang.Integer getCustinfoId() {
		return get("custinfo_id");
	}

	public void setApplicationMethod(java.lang.String applicationMethod) {
		set("application_method", applicationMethod);
	}

	public java.lang.String getApplicationMethod() {
		return get("application_method");
	}

	public void setInvitationCode(java.lang.String invitationCode) {
		set("invitation_code", invitationCode);
	}

	public java.lang.String getInvitationCode() {
		return get("invitation_code");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setArticipateFlag(java.lang.Integer articipateFlag) {
		set("articipate_flag", articipateFlag);
	}

	public java.lang.Integer getArticipateFlag() {
		return get("articipate_flag");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setOnlineStatus(java.lang.String onlineStatus) {
		set("online_status", onlineStatus);
	}

	public java.lang.String getOnlineStatus() {
		return get("online_status");
	}

	public void setOnlineTime(java.util.Date onlineTime) {
		set("online_time", onlineTime);
	}

	public java.util.Date getOnlineTime() {
		return get("online_time");
	}

	public void setCancelTime(java.util.Date cancelTime) {
		set("cancel_time", cancelTime);
	}

	public java.util.Date getCancelTime() {
		return get("cancel_time");
	}

	public void setCancelOperator(java.lang.Integer cancelOperator) {
		set("cancel_operator", cancelOperator);
	}

	public java.lang.Integer getCancelOperator() {
		return get("cancel_operator");
	}

	public void setCancelOperatorName(java.lang.String cancelOperatorName) {
		set("cancel_operator_name", cancelOperatorName);
	}

	public java.lang.String getCancelOperatorName() {
		return get("cancel_operator_name");
	}

}
