package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStewardUser<M extends BaseStewardUser<M>> extends Model<M> implements IBean {

	public void setStewardId(java.lang.Integer stewardId) {
		set("steward_id", stewardId);
	}

	public java.lang.Integer getStewardId() {
		return get("steward_id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
	}

	public java.lang.Integer getDeleteFlag() {
		return get("delete_flag");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
	}

	public java.lang.String getCreateUser() {
		return get("create_user");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
	}

	public java.lang.String getUpdateUser() {
		return get("update_user");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setReleaseMark(java.lang.String releaseMark) {
		set("release_mark", releaseMark);
	}

	public java.lang.String getReleaseMark() {
		return get("release_mark");
	}

	public void setStewardCode(java.lang.String stewardCode) {
		set("steward_code", stewardCode);
	}

	public java.lang.String getStewardCode() {
		return get("steward_code");
	}

	public void setStewardPcode(java.lang.String stewardPcode) {
		set("steward_pcode", stewardPcode);
	}

	public java.lang.String getStewardPcode() {
		return get("steward_pcode");
	}

	public void setEmployCount(java.lang.Integer employCount) {
		set("employ_count", employCount);
	}

	public java.lang.Integer getEmployCount() {
		return get("employ_count");
	}

	public void setCardStatus(java.lang.Integer cardStatus) {
		set("card_status", cardStatus);
	}

	public java.lang.Integer getCardStatus() {
		return get("card_status");
	}

	public void setLikeCount(java.lang.Integer likeCount) {
		set("like_count", likeCount);
	}

	public java.lang.Integer getLikeCount() {
		return get("like_count");
	}

	public void setExpertCountry(java.lang.String expertCountry) {
		set("expert_country", expertCountry);
	}

	public java.lang.String getExpertCountry() {
		return get("expert_country");
	}

}
