package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBusinessNegotiation<M extends BaseBusinessNegotiation<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCooperationId(java.lang.Integer cooperationId) {
		set("cooperation_id", cooperationId);
	}

	public java.lang.Integer getCooperationId() {
		return get("cooperation_id");
	}

	public void setNegotiationStatus(java.lang.String negotiationStatus) {
		set("negotiation_status", negotiationStatus);
	}

	public java.lang.String getNegotiationStatus() {
		return get("negotiation_status");
	}

	public void setNegotiationExplain(java.lang.String negotiationExplain) {
		set("negotiation_explain", negotiationExplain);
	}

	public java.lang.String getNegotiationExplain() {
		return get("negotiation_explain");
	}

	public void setNegotiationTime(java.util.Date negotiationTime) {
		set("negotiation_time", negotiationTime);
	}

	public java.util.Date getNegotiationTime() {
		return get("negotiation_time");
	}

	public void setNegotiationUser(java.lang.String negotiationUser) {
		set("negotiation_user", negotiationUser);
	}

	public java.lang.String getNegotiationUser() {
		return get("negotiation_user");
	}

}
