package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePageFooters<M extends BasePageFooters<M>> extends Model<M> implements IBean {

	public void setPageFootersId(java.lang.Integer pageFootersId) {
		set("page_footers_id", pageFootersId);
	}

	public java.lang.Integer getPageFootersId() {
		return get("page_footers_id");
	}

	public void setLogoImg(java.lang.String logoImg) {
		set("logo_img", logoImg);
	}

	public java.lang.String getLogoImg() {
		return get("logo_img");
	}

	public void setCompanyName(java.lang.String companyName) {
		set("company_name", companyName);
	}

	public java.lang.String getCompanyName() {
		return get("company_name");
	}

	public void setCompanyAdd(java.lang.String companyAdd) {
		set("company_add", companyAdd);
	}

	public java.lang.String getCompanyAdd() {
		return get("company_add");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setServiceHotline(java.lang.String serviceHotline) {
		set("service_hotline", serviceHotline);
	}

	public java.lang.String getServiceHotline() {
		return get("service_hotline");
	}

	public void setCustomerHotline(java.lang.String customerHotline) {
		set("customer_hotline", customerHotline);
	}

	public java.lang.String getCustomerHotline() {
		return get("customer_hotline");
	}

	public void setWxImgOne(java.lang.String wxImgOne) {
		set("wx_img_one", wxImgOne);
	}

	public java.lang.String getWxImgOne() {
		return get("wx_img_one");
	}

	public void setWxImgTwo(java.lang.String wxImgTwo) {
		set("wx_img_two", wxImgTwo);
	}

	public java.lang.String getWxImgTwo() {
		return get("wx_img_two");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
