package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDistributionScale<M extends BaseDistributionScale<M>> extends Model<M> implements IBean {

	public void setDistributionScaleId(java.lang.Integer distributionScaleId) {
		set("distribution_scale_id", distributionScaleId);
	}

	public java.lang.Integer getDistributionScaleId() {
		return get("distribution_scale_id");
	}

	public void setDistributionTypeId(java.lang.Integer distributionTypeId) {
		set("distribution_type_id", distributionTypeId);
	}

	public java.lang.Integer getDistributionTypeId() {
		return get("distribution_type_id");
	}

	public void setDistributionTypeName(java.lang.String distributionTypeName) {
		set("distribution_type_name", distributionTypeName);
	}

	public java.lang.String getDistributionTypeName() {
		return get("distribution_type_name");
	}

	public void setDistributionTypeScale(java.lang.String distributionTypeScale) {
		set("distribution_type_scale", distributionTypeScale);
	}

	public java.lang.String getDistributionTypeScale() {
		return get("distribution_type_scale");
	}

	public void setModelType(java.lang.String modelType) {
		set("model_type", modelType);
	}

	public java.lang.String getModelType() {
		return get("model_type");
	}

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

	public void setLevel1Scale(java.lang.String level1Scale) {
		set("level_1_scale", level1Scale);
	}

	public java.lang.String getLevel1Scale() {
		return get("level_1_scale");
	}

	public void setLevel2Scale(java.lang.String level2Scale) {
		set("level_2_scale", level2Scale);
	}

	public java.lang.String getLevel2Scale() {
		return get("level_2_scale");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
