package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAddressProvince<M extends BaseAddressProvince<M>> extends Model<M> implements IBean {

	public void setProvinceId(java.lang.String ProvinceId) {
		set("ProvinceId", ProvinceId);
	}

	public java.lang.String getProvinceId() {
		return get("ProvinceId");
	}

	public void setCountryId(java.lang.String CountryId) {
		set("CountryId", CountryId);
	}

	public java.lang.String getCountryId() {
		return get("CountryId");
	}

	public void setProvinceName(java.lang.String ProvinceName) {
		set("ProvinceName", ProvinceName);
	}

	public java.lang.String getProvinceName() {
		return get("ProvinceName");
	}

	public void setQuickCode(java.lang.String QuickCode) {
		set("QuickCode", QuickCode);
	}

	public java.lang.String getQuickCode() {
		return get("QuickCode");
	}

	public void setDescription(java.lang.String Description) {
		set("Description", Description);
	}

	public java.lang.String getDescription() {
		return get("Description");
	}

	public void setVersionNumber(java.lang.Integer VersionNumber) {
		set("VersionNumber", VersionNumber);
	}

	public java.lang.Integer getVersionNumber() {
		return get("VersionNumber");
	}

}
