package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxWeixinResource<M extends BaseWxWeixinResource<M>> extends Model<M> implements IBean {

	public void setWeixinResourceId(java.lang.Integer weixinResourceId) {
		set("weixin_resource_id", weixinResourceId);
	}

	public java.lang.Integer getWeixinResourceId() {
		return get("weixin_resource_id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setOpenid(java.lang.String openid) {
		set("openid", openid);
	}

	public java.lang.String getOpenid() {
		return get("openid");
	}

	public void setWxName(java.lang.String wxName) {
		set("wx_name", wxName);
	}

	public java.lang.String getWxName() {
		return get("wx_name");
	}

	public void setHeadImg(java.lang.String headImg) {
		set("head_img", headImg);
	}

	public java.lang.String getHeadImg() {
		return get("head_img");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateUser(java.lang.Integer createUser) {
		set("create_user", createUser);
	}

	public java.lang.Integer getCreateUser() {
		return get("create_user");
	}

}
