package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStewardLike<M extends BaseStewardLike<M>> extends Model<M> implements IBean {

	public void setLikeId(java.lang.Integer likeId) {
		set("like_id", likeId);
	}

	public java.lang.Integer getLikeId() {
		return get("like_id");
	}

	public void setStewardId(java.lang.Integer stewardId) {
		set("steward_id", stewardId);
	}

	public java.lang.Integer getStewardId() {
		return get("steward_id");
	}

	public void setCustinfoId(java.lang.Integer custinfoId) {
		set("custinfo_id", custinfoId);
	}

	public java.lang.Integer getCustinfoId() {
		return get("custinfo_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
