package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDistributionSet<M extends BaseDistributionSet<M>> extends Model<M> implements IBean {

	public void setDistributionSetId(java.lang.Integer distributionSetId) {
		set("distribution_set_id", distributionSetId);
	}

	public java.lang.Integer getDistributionSetId() {
		return get("distribution_set_id");
	}

	public void setModelType(java.lang.String modelType) {
		set("model_type", modelType);
	}

	public java.lang.String getModelType() {
		return get("model_type");
	}

	public void setCliMainId(java.lang.Integer cliMainId) {
		set("cli_main_id", cliMainId);
	}

	public java.lang.Integer getCliMainId() {
		return get("cli_main_id");
	}

	public void setOneLevelParentId(java.lang.Integer oneLevelParentId) {
		set("one_level_parent_id", oneLevelParentId);
	}

	public java.lang.Integer getOneLevelParentId() {
		return get("one_level_parent_id");
	}

	public void setOneLevelParentScale(java.lang.Double oneLevelParentScale) {
		set("one_level_parent_scale", oneLevelParentScale);
	}

	public java.lang.Double getOneLevelParentScale() {
		return get("one_level_parent_scale");
	}

	public void setTwoLevelParentId(java.lang.Integer twoLevelParentId) {
		set("two_level_parent_id", twoLevelParentId);
	}

	public java.lang.Integer getTwoLevelParentId() {
		return get("two_level_parent_id");
	}

	public void setTwoLevelParentScale(java.lang.Double twoLevelParentScale) {
		set("two_level_parent_scale", twoLevelParentScale);
	}

	public java.lang.Double getTwoLevelParentScale() {
		return get("two_level_parent_scale");
	}

	public void setTwoLevelGrandparentId(java.lang.Integer twoLevelGrandparentId) {
		set("two_level_grandparent_id", twoLevelGrandparentId);
	}

	public java.lang.Integer getTwoLevelGrandparentId() {
		return get("two_level_grandparent_id");
	}

	public void setTwoLevelGrandparentScale(java.lang.Double twoLevelGrandparentScale) {
		set("two_level_grandparent_scale", twoLevelGrandparentScale);
	}

	public java.lang.Double getTwoLevelGrandparentScale() {
		return get("two_level_grandparent_scale");
	}

	public void setProjectId(java.lang.Integer projectId) {
		set("project_id", projectId);
	}

	public java.lang.Integer getProjectId() {
		return get("project_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
