package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOperationLog<M extends BaseOperationLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setOptType(java.lang.String optType) {
		set("opt_type", optType);
	}

	public java.lang.String getOptType() {
		return get("opt_type");
	}

	public void setOptDescription(java.lang.String optDescription) {
		set("opt_description", optDescription);
	}

	public java.lang.String getOptDescription() {
		return get("opt_description");
	}

	public void setOptModule(java.lang.String optModule) {
		set("opt_module", optModule);
	}

	public java.lang.String getOptModule() {
		return get("opt_module");
	}

	public void setOptUser(java.lang.String optUser) {
		set("opt_user", optUser);
	}

	public java.lang.String getOptUser() {
		return get("opt_user");
	}

	public void setOptTime(java.util.Date optTime) {
		set("opt_time", optTime);
	}

	public java.util.Date getOptTime() {
		return get("opt_time");
	}

}
