package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCopyright<M extends BaseCopyright<M>> extends Model<M> implements IBean {

	public void setCopyrightId(java.lang.Integer copyrightId) {
		set("copyright_id", copyrightId);
	}

	public java.lang.Integer getCopyrightId() {
		return get("copyright_id");
	}

	public void setCompanyName(java.lang.String companyName) {
		set("company_name", companyName);
	}

	public java.lang.String getCompanyName() {
		return get("company_name");
	}

	public void setCopyright(java.lang.String copyright) {
		set("copyright", copyright);
	}

	public java.lang.String getCopyright() {
		return get("copyright");
	}

	public void setRecordation(java.lang.String recordation) {
		set("recordation", recordation);
	}

	public java.lang.String getRecordation() {
		return get("recordation");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
