package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserStation<M extends BaseUserStation<M>> extends Model<M> implements IBean {

	public void setStationId(java.lang.Integer stationId) {
		set("station_id", stationId);
	}

	public java.lang.Integer getStationId() {
		return get("station_id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

}
