package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStewardSign<M extends BaseStewardSign<M>> extends Model<M> implements IBean {

	public void setSignId(java.lang.Integer signId) {
		set("sign_id", signId);
	}

	public java.lang.Integer getSignId() {
		return get("sign_id");
	}

	public void setStewardId(java.lang.Integer stewardId) {
		set("steward_id", stewardId);
	}

	public java.lang.Integer getStewardId() {
		return get("steward_id");
	}

	public void setCustinfoId(java.lang.Integer custinfoId) {
		set("custinfo_id", custinfoId);
	}

	public java.lang.Integer getCustinfoId() {
		return get("custinfo_id");
	}

	public void setSignStatus(java.lang.String signStatus) {
		set("sign_status", signStatus);
	}

	public java.lang.String getSignStatus() {
		return get("sign_status");
	}

	public void setSignTime(java.util.Date signTime) {
		set("sign_time", signTime);
	}

	public java.util.Date getSignTime() {
		return get("sign_time");
	}

	public void setUnsignTime(java.util.Date unsignTime) {
		set("unsign_time", unsignTime);
	}

	public java.util.Date getUnsignTime() {
		return get("unsign_time");
	}

	public void setUnsignReason(java.lang.String unsignReason) {
		set("unsign_reason", unsignReason);
	}

	public java.lang.String getUnsignReason() {
		return get("unsign_reason");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
