package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStewardEvaluate<M extends BaseStewardEvaluate<M>> extends Model<M> implements IBean {

	public void setEvaluateId(java.lang.Integer evaluateId) {
		set("evaluate_id", evaluateId);
	}

	public java.lang.Integer getEvaluateId() {
		return get("evaluate_id");
	}

	public void setStewardId(java.lang.Integer stewardId) {
		set("steward_id", stewardId);
	}

	public java.lang.Integer getStewardId() {
		return get("steward_id");
	}

	public void setCustinfoId(java.lang.Integer custinfoId) {
		set("custinfo_id", custinfoId);
	}

	public java.lang.Integer getCustinfoId() {
		return get("custinfo_id");
	}

	public void setStarLevel(java.lang.Float starLevel) {
		set("star_level", starLevel);
	}

	public java.lang.Float getStarLevel() {
		return get("star_level");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setServiceAttitude(java.lang.Integer serviceAttitude) {
		set("service_attitude", serviceAttitude);
	}

	public java.lang.Integer getServiceAttitude() {
		return get("service_attitude");
	}

	public void setSpecializedKnowledge(java.lang.Integer specializedKnowledge) {
		set("specialized_knowledge", specializedKnowledge);
	}

	public java.lang.Integer getSpecializedKnowledge() {
		return get("specialized_knowledge");
	}

	public void setFeedbackEfficiency(java.lang.Integer feedbackEfficiency) {
		set("feedback_efficiency", feedbackEfficiency);
	}

	public java.lang.Integer getFeedbackEfficiency() {
		return get("feedback_efficiency");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
	}

	public java.lang.Integer getDeleteFlag() {
		return get("delete_flag");
	}

	public void setHidden(java.lang.Integer hidden) {
		set("hidden", hidden);
	}

	public java.lang.Integer getHidden() {
		return get("hidden");
	}

	public void setHiddenReason(java.lang.String hiddenReason) {
		set("hidden_reason", hiddenReason);
	}

	public java.lang.String getHiddenReason() {
		return get("hidden_reason");
	}

}
