package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLive<M extends BaseLive<M>> extends Model<M> implements IBean {

	public void setLiveId(java.lang.Integer liveId) {
		set("live_id", liveId);
	}

	public java.lang.Integer getLiveId() {
		return get("live_id");
	}

	public void setLiveTitle(java.lang.String liveTitle) {
		set("live_title", liveTitle);
	}

	public java.lang.String getLiveTitle() {
		return get("live_title");
	}

	public void setLiveStewardId(java.lang.Integer liveStewardId) {
		set("live_steward_id", liveStewardId);
	}

	public java.lang.Integer getLiveStewardId() {
		return get("live_steward_id");
	}

	public void setLiveLimit(java.lang.Integer liveLimit) {
		set("live_limit", liveLimit);
	}

	public java.lang.Integer getLiveLimit() {
		return get("live_limit");
	}

	public void setLiveIntroduce(java.lang.String liveIntroduce) {
		set("live_introduce", liveIntroduce);
	}

	public java.lang.String getLiveIntroduce() {
		return get("live_introduce");
	}

	public void setLivePoster(java.lang.String livePoster) {
		set("live_poster", livePoster);
	}

	public java.lang.String getLivePoster() {
		return get("live_poster");
	}

	public void setLiveStatus(java.lang.String liveStatus) {
		set("live_status", liveStatus);
	}

	public java.lang.String getLiveStatus() {
		return get("live_status");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
	}

	public java.lang.Integer getDeleteFlag() {
		return get("delete_flag");
	}

	public void setSignupStartTime(java.util.Date signupStartTime) {
		set("signup_start_time", signupStartTime);
	}

	public java.util.Date getSignupStartTime() {
		return get("signup_start_time");
	}

	public void setSignupEndTime(java.util.Date signupEndTime) {
		set("signup_end_time", signupEndTime);
	}

	public java.util.Date getSignupEndTime() {
		return get("signup_end_time");
	}

	public void setSignupNum(java.lang.Integer signupNum) {
		set("signup_num", signupNum);
	}

	public java.lang.Integer getSignupNum() {
		return get("signup_num");
	}

	public void setTempSignupNum(java.lang.Integer tempSignupNum) {
		set("temp_signup_num", tempSignupNum);
	}

	public java.lang.Integer getTempSignupNum() {
		return get("temp_signup_num");
	}

	public void setChannelId(java.lang.Integer channelId) {
		set("channel_id", channelId);
	}

	public java.lang.Integer getChannelId() {
		return get("channel_id");
	}

	public void setLiveType(java.lang.String liveType) {
		set("live_type", liveType);
	}

	public java.lang.String getLiveType() {
		return get("live_type");
	}

	public void setLiveStartTime(java.util.Date liveStartTime) {
		set("live_start_time", liveStartTime);
	}

	public java.util.Date getLiveStartTime() {
		return get("live_start_time");
	}

	public void setLiveEndTime(java.util.Date liveEndTime) {
		set("live_end_time", liveEndTime);
	}

	public java.util.Date getLiveEndTime() {
		return get("live_end_time");
	}

}
