package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHonor<M extends BaseHonor<M>> extends Model<M> implements IBean {

	public void setOhId(java.lang.Integer ohId) {
		set("oh_id", ohId);
	}

	public java.lang.Integer getOhId() {
		return get("oh_id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}

	public java.lang.Integer getSort() {
		return get("sort");
	}

	public void setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
	}

	public java.lang.Integer getDeleteFlag() {
		return get("delete_flag");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCteator(java.lang.String cteator) {
		set("cteator", cteator);
	}

	public java.lang.String getCteator() {
		return get("cteator");
	}

	public void setEditTime(java.util.Date editTime) {
		set("edit_time", editTime);
	}

	public java.util.Date getEditTime() {
		return get("edit_time");
	}

	public void setEditor(java.lang.String editor) {
		set("editor", editor);
	}

	public java.lang.String getEditor() {
		return get("editor");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

}
