package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustinfoSteward<M extends BaseCustinfoSteward<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setCustinfoId(java.lang.Integer custinfoId) {
		set("custinfo_id", custinfoId);
	}

	public java.lang.Integer getCustinfoId() {
		return get("custinfo_id");
	}

	public void setStewardId(java.lang.Integer stewardId) {
		set("steward_id", stewardId);
	}

	public java.lang.Integer getStewardId() {
		return get("steward_id");
	}

	public void setIsHire(java.lang.Integer isHire) {
		set("is_hire", isHire);
	}

	public java.lang.Integer getIsHire() {
		return get("is_hire");
	}

	public void setHireDate(java.util.Date hireDate) {
		set("hire_date", hireDate);
	}

	public java.util.Date getHireDate() {
		return get("hire_date");
	}

}
