package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseChannel<M extends BaseChannel<M>> extends Model<M> implements IBean {

	public void setChannelId(java.lang.Integer channelId) {
		set("channel_id", channelId);
	}

	public java.lang.Integer getChannelId() {
		return get("channel_id");
	}

	public void setCid(java.lang.String cid) {
		set("cid", cid);
	}

	public java.lang.String getCid() {
		return get("cid");
	}

	public void setCtime(java.util.Date ctime) {
		set("ctime", ctime);
	}

	public java.util.Date getCtime() {
		return get("ctime");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setPushUrl(java.lang.String pushUrl) {
		set("pushUrl", pushUrl);
	}

	public java.lang.String getPushUrl() {
		return get("pushUrl");
	}

	public void setHttpPullUrl(java.lang.String httpPullUrl) {
		set("httpPullUrl", httpPullUrl);
	}

	public java.lang.String getHttpPullUrl() {
		return get("httpPullUrl");
	}

	public void setHlsPullUrl(java.lang.String hlsPullUrl) {
		set("hlsPullUrl", hlsPullUrl);
	}

	public java.lang.String getHlsPullUrl() {
		return get("hlsPullUrl");
	}

	public void setRtmpPullUrl(java.lang.String rtmpPullUrl) {
		set("rtmpPullUrl", rtmpPullUrl);
	}

	public java.lang.String getRtmpPullUrl() {
		return get("rtmpPullUrl");
	}

	public void setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
	}

	public java.lang.Integer getDeleteFlag() {
		return get("delete_flag");
	}

	public void setUsed(java.lang.Integer used) {
		set("used", used);
	}

	public java.lang.Integer getUsed() {
		return get("used");
	}

}
