package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseActivitySign<M extends BaseActivitySign<M>> extends Model<M> implements IBean {

	public void setSignId(java.lang.Integer signId) {
		set("sign_id", signId);
	}

	public java.lang.Integer getSignId() {
		return get("sign_id");
	}

	public void setSignName(java.lang.String signName) {
		set("sign_name", signName);
	}

	public java.lang.String getSignName() {
		return get("sign_name");
	}

	public void setSignMobile(java.lang.String signMobile) {
		set("sign_mobile", signMobile);
	}

	public java.lang.String getSignMobile() {
		return get("sign_mobile");
	}

	public void setSignNum(java.lang.Integer signNum) {
		set("sign_num", signNum);
	}

	public java.lang.Integer getSignNum() {
		return get("sign_num");
	}

	public void setSignUser(java.lang.String signUser) {
		set("sign_user", signUser);
	}

	public java.lang.String getSignUser() {
		return get("sign_user");
	}

	public void setSignTime(java.util.Date signTime) {
		set("sign_time", signTime);
	}

	public java.util.Date getSignTime() {
		return get("sign_time");
	}

	public void setActivityId(java.lang.Integer activityId) {
		set("activity_id", activityId);
	}

	public java.lang.Integer getActivityId() {
		return get("activity_id");
	}

}
