package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProjectCost<M extends BaseProjectCost<M>> extends Model<M> implements IBean {

	public void setProjectCostId(java.lang.Integer projectCostId) {
		set("project_cost_id", projectCostId);
	}

	public java.lang.Integer getProjectCostId() {
		return get("project_cost_id");
	}

	public void setProjectId(java.lang.Integer projectId) {
		set("project_id", projectId);
	}

	public java.lang.Integer getProjectId() {
		return get("project_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setInstitution(java.lang.String institution) {
		set("institution", institution);
	}

	public java.lang.String getInstitution() {
		return get("institution");
	}

	public void setCost(java.lang.String cost) {
		set("cost", cost);
	}

	public java.lang.String getCost() {
		return get("cost");
	}

	public void setChargeStage(java.lang.String chargeStage) {
		set("charge_stage", chargeStage);
	}

	public java.lang.String getChargeStage() {
		return get("charge_stage");
	}

	public void setRefundStandard(java.lang.String refundStandard) {
		set("refund_standard", refundStandard);
	}

	public java.lang.String getRefundStandard() {
		return get("refund_standard");
	}

	public void setPriority(java.lang.Integer priority) {
		set("priority", priority);
	}

	public java.lang.Integer getPriority() {
		return get("priority");
	}

	public void setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
	}

	public java.lang.Integer getDeleteFlag() {
		return get("delete_flag");
	}

}
